#!/bin/sh
#
# Initialization file for the kernel-service daemon.
#
# chkconfig: - 90 10
# description:  A service that collects information about software updates \
#               and system kernel versions for the kernel indicator in the \
#               system tray.
# processname: kernel-service
# pidfile: /var/run/kernel-service.pid
#
### BEGIN INIT INFO
# Provides:          kernel-service
# Required-Start:    $local_fs $syslog
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Service for kernel-indicator
# Description:       A service for collecting information about software and \
#                    system kernel updates for kernel-indicator.
### END INIT INFO
#
# Do not load RH compatibility interface.
WITHOUT_RC_COMPAT=1

# Source function library.
. /etc/rc.d/init.d/functions

PIDFILE=/var/run/kernel-service.pid
LOCKFILE=/var/lock/subsys/kernel-service
RETVAL=0

start()
{
	start_daemon --make-pidfile --pidfile "$PIDFILE" --lockfile "$LOCKFILE" --expect-user root -- kernel-service
	RETVAL=$?
	return $RETVAL
}

stop()
{
	stop_daemon --pidfile "$PIDFILE" --lockfile "$LOCKFILE" --expect-user root -- kernel-service
	RETVAL=$?
	return $RETVAL
}

restart()
{
	stop
	start
}

# See how we were called.
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload|restart)
		restart
		;;
	condstop)
		if [ -e "$LOCKFILE" ]; then
			stop
		fi
		;;
    condreload|condrestart)
		if [ -e "$LOCKFILE" ]; then
			restart
		fi
		;;
	status)
		status --pidfile "$PIDFILE" --expect-user root -- kernel-service
		RETVAL=$?
		;;
	*)
		msg_usage "${0##*/} {start|stop|reload|restart|condstop|condrestart|condreload|status}"
		RETVAL=1
esac

exit $RETVAL
